name: Go Releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write # SLSA için gerekli izin

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.22'] # Go versiyonunu belirt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: go build -o nessusmerger-${{ matrix.os }}.exe ./...

      - name: Build on Linux and macOS
        if: runner.os != 'Windows'
        run: go build -o nessusmerger-${{ matrix.os }} ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nessusmerger-${{ matrix.os }}
          path: nessusmerger-${{ matrix.os }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          tag_name: "nessusmerger!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
